### GET ALL THREADS
GET http://localhost:3001/threads-services

### GET THREAD By:id
GET http://localhost:3001/threads-services/66d74b86189e432b4f4fd55c

### CREATE THREADS
POST http://localhost:3001/threads-services
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTA3NmJhNjRlNzZjNjQ2N2JmZjFjZCIsIm5hbWUiOiJBc2VwIiwiZW1haWwiOiJhc2VwamF5YUBnbWFpbC5jb20iLCJpYXQiOjE3MjYxMTc1MTMsImV4cCI6MTcyNjExNzgxM30.9nyowbSBZ8yFP1phQAKPiGTg90uCLbRLpIHfBYCo8is;refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTA3NmJhNjRlNzZjNjQ2N2JmZjFjZCIsIm5hbWUiOiJBc2VwIiwiZW1haWwiOiJhc2VwamF5YUBnbWFpbC5jb20iLCJpYXQiOjE3MjYxMTc1MTMsImV4cCI6MTcyNjcyMjMxM30.pQjOjxIpMXwuCQNoRCClPdATpo1VeDHkXbDNp54PsOc

{
  "title": "Threads Asep",
  "body": "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
}

### UPDATE THREAD
PATCH http://localhost:3001/threads-services/66d74b86189e432b4f4fd55c
Content-Type: application/json

{
  "title": "Thread Update",
  "body": "Lorem ipsum dolor sit amet."
}

### DELETE THREAD
DELETE http://localhost:3001/threads-services/66da1c270c05237913ab093e

### logout
POST http://localhost:3001/auth/logout